--simple sql

CREATE DATABASE escola;
CREATE TABLE escola.alunos(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
telefone VARCHAR(25) NOT NULL
);

CREATE TABLE biblioteca(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
livros VARCHAR(80) NOT NULL,
disponibilidade BOOLEAN DEFAULT TRUE
);

CREATE TABLE escola.reservas(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_alunos INT NOT NULL,
FOREIGN KEY(id_alunos) REFERENCES alunos(id),
id_biblioteca INT NOT NULL,
FOREIGN KEY(id_biblioteca) REFERENCES biblioteca(id)
);



